### PR TITLE
Jhu357

### PR DESCRIPTION
**Pull request by justinjiaxinghu**

### CODE REVIEW

**Comment by JasonGibson274** [comment]
That is worse

**Comment by justinjiaxinghu** [comment]
> That is worse

can you tell me what's wrong with it

**Comment by JasonGibson274** [comment]
Well it does not look like plus

**Comment by justinjiaxinghu** [comment]
> Well it does not look like plus

so it's the quality of the ascii image?

**Comment by JasonGibson274** [comment]
No, it looks like something else that I am *not* merging into this repo

**Comment by justinjiaxinghu** [comment]
> No, it looks like something else that I am _**not**_ merging into this repo

ok well i changed it again is it ok this time

**Pull request merged**
